name: 'Upload to Google Drive (forked)'
description: 'Uploads a file or a folder to Google Drive'
author: 'Yayo Acosta & Max Isom'
inputs:
  credentials:
    description: 'Google Service Account credentials'
    required: true
  uploadOrDownload:
    description: 'download or upload'
    required: true
  folderOrfileID:
    description: 'Google Drive folder ID to upload the file/folder to or file ID to download'
    required: true
  target:
    description: 'Local path to the file/folder to upload or to filepath to download'
    required: true
  name:
    description: 'Optional name for the zipped file'
    required: false
    default: null
outputs:
  link:
    description: 'A link to the Drive folder'
  refId:
    description: 'Id of the uploaded file'
  fileLink:
    description: 'A direct link to the uploaded file'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'
  color: 'orange'
